### ISSUE TITLE
basset:fresh causing timeout error

### ISSUE THREAD

**Issue by hagealex** [Laravel-Backpack/basset#101]
Hello everyone!

I update my application from Backpack 5 to 6 and now, during my CI, I have a problem that occurs from time to time.

In my post-install-cmd in my composer.json I run `php artisan basset:fresh`. Sometimes I get this error:

```
In PendingProcess.php line 258:
The process "php artisan basset:cache" exceeded the timeout of 60 seconds.

In PendingProcess.php line 1158:
The process "php artisan basset:cache" exceeded the timeout of 60 seconds.
```

Is there something I can do to prevent this error?

**Comment by pxpm** [comment]
Hey @hagealex 

I think the only solution would be to increase the time that script can run.

You can do it globally by changing the `php.ini` settings in your webserver (probably not recommended). 

Or alternatively you can allow only the `basset:cache` command to exceed those limits by calling:
```bash
php artisan basset:clear && php -d max_execution_time=120 artisan basset:cache
```

Let me know if that solved the issue for you.

Cheers.

**Comment by hagealex** [comment]
@pxpm This seems to work. I'll check this during my nexts builds.

Thank you so much for your hint!
