### ISSUE TITLE
Basset behind HTTP Proxy

### ISSUE THREAD

**Issue by sebiecker** [Laravel-Backpack/basset#111]
Hi!

I would like to use Basset in a DMZ without active Internet access. 

Please provide options to configure a explizit HTTP Proxy for the HTTP Client in fetchContent function.

**Comment by karandatwani92** [comment]
Hey @sebiecker 

You would require the internet once to copy assets from CDNs to your local server.
The command `php artisan basset:cache` will go through all your blade files, and internalize everything possible.

Notes:
- Ensure that APP_URL in your .env matches your server configuration, including the hostname, protocol, and port number. Incorrect settings can lead to asset-loading issues.
- Basset is disabled by default on local environment. If you want to change it, please set BASSET_DEV_MODE=false

Find more info [here](https://github.com/Laravel-Backpack/basset?tab=readme-ov-file#the-basset-commands)

**Comment by sebiecker** [comment]
@karandatwani92 but that not possible without the proxy settings.. The Server can only reach the internet via HTTP Proxy

**Comment by pxpm** [comment]
Hey @sebiecker 

You can upload the files `basset:cache` generates on your filesystem (by default in: `storage\app\public\basset`), including the `.basset` file, the cache map of the internalized assets. 

Don't forget to do the storage link in case you haven't done it already, it's in basset docs.

That way in your internet free zone you will always use the assets you internalized previously in your local machine.

Let me know if that helps. 

Cheers
