### ISSUE TITLE
the problem is always here with 1.3.1

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/basset#121]
the problem is always here with 1.3.1

![image](https://github.com/Laravel-Backpack/basset/assets/3491828/37afcfc6-8b3b-4d7c-8c95-87969b3c382f)

_Originally posted by @dauvray in https://github.com/Laravel-Backpack/basset/issues/119#issuecomment-2051572850_

**Comment by dauvray** [comment]
it works if i put BASSET_DEV_MODE=false in my .env.
if i remove it, it fails

**Comment by pxpm** [comment]
It seems to be a temporary issue. 
https://www.cloudflarestatus.com/incidents/fjh89m55qxt7

In Portugal where I am located is already working fine. 

Please allow a few more moments and you should be able too.

**Comment by pxpm** [comment]
Closing, let me know if you are still experiencing issues. 🙏
