### ISSUE TITLE
Cannot assign null to property Backpack\Basset\Helpers\CacheMap::$map of type array

### ISSUE THREAD

**Issue by amirfaraz88** [Laravel-Backpack/basset#123]
It was working fine in the morning. However, after the Windows auto-update and restart, the issue occurred

Cannot assign null to property Backpack\Basset\Helpers\CacheMap::$map of type array

Is there a way to resolve the issue?

Best regards,
Amir Faraz

**Comment by karandatwani92** [comment]
Hey @amirfaraz88 

Can you share the output of `php artisan backpack:version`? This may help us identify the issue.
Also, you can try `composer update`.

Basset is working fine, I doubt your system's PHP version got changed.

**Comment by amirfaraz88** [comment]
Hey @karandatwani92 

### PHP VERSION:
PHP 8.1.10 (cli) (built: Aug 30 2022 18:05:49) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.22.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/backupmanager: v5.0.0
backpack/basset: 1.2.0
backpack/crud: 6.6.4
backpack/editable-columns: 3.0.2
backpack/generators: v4.0.2
backpack/logmanager: v5.0.0
backpack/pagemanager: 3.2.0
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/settings: 3.1.0
backpack/theme-coreuiv2: 1.2.0
backpack/theme-coreuiv4: 1.1.0
backpack/theme-tabler: 1.1.0

thanks for help

**Comment by amirfaraz88** [comment]
I tried on **composer update** then I encountered GitHub repository not found issue

Failed to execute git clone --mirror -- https://ghp...CNU:x-oauth-basic@github.com/Laravel-Backpack/PRO.git C:/Users/Admin/AppData/Local/Composer/vcs/git-github.
  com-Laravel-Backpack-PRO.git/

  Cloning into bare repository 'C:/Users/Admin/AppData/Local/Composer/vcs/git-github.com-Laravel-Backpack-PRO.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/Laravel-Backpack/PRO.git/' not found

**Comment by karandatwani92** [comment]
Can you set the credentials again and retry? Instructions are available [here](https://backpackforlaravel.com/user/tokens)
