### ISSUE TITLE
Having an issue with basset Fetching While installing backpack

### ISSUE THREAD

**Issue by ahmedshahd** [Laravel-Backpack/basset#124]
i got this issue while trying to install backpack 
i am using laravel 10 and valet as dev env

this  the issue 
<img width="877" alt="Screenshot 2024-04-16 at 6 49 56 AM" src="https://github.com/Laravel-Backpack/basset/assets/48631752/f27338a4-c20f-4cd8-a208-3c8f0a626bc6">

i checked .env file  
APP_ENV=local
APP_URL=https://real-estate.test

when i use APP_URL=http://localhost:8000 it works well, but i want to make it work in https for valet

**Comment by karandatwani92** [comment]
Hey @ahmedshahd 

Did you run `valet secure` in the folder to make it work with `https`?
