### ISSUE TITLE
Format URL issue with files from package

### ISSUE THREAD

**Issue by dauvray** [Laravel-Backpack/basset#128]
Hello,

I can't figure out why the files coming from the package are poorly formatted, while those coming from the cdn are fine.

@basset(base_path('vendor/backpack/crud/src/resources/assets/css/common.css'))

this line give me : 
https://my-domain.com/var/www/my-app/vendor/backpack/crud/src/resources/assets/css/common.css?51f5b8a02400
instead of
https://my-domain.com/storage/basset/vendor/backpack/crud/src/resources/assets/css/common.css?51f5b8a02400

same thing with common.js

**Comment by karandatwani92** [comment]
Hey @dauvray 

What do you mean by `poorly formatted`?

`@basset()` is meant to copy the files from cdn to the server's local storage `storage/app/public/basset` and serve from there only.

If you want to disable this behavior, add `BASSET_DEV_MODE=true` to `.env` to disable this feature.

**Comment by dauvray** [comment]
i have BASSET_DEV_MODE=true  in .env
when i say "poorly formatted" ( google trad ) i mean in my url you can see the path in my serveur : /var/www/my-app

 I'm workin with a fake domain name via my host file in windows to my nginx server. maybe this is the problem ?

**Comment by karandatwani92** [comment]
Oh! Sorry I didn't notice that. can you share your .env's `APP_URL` & `ASSET_URL`?

**Comment by dauvray** [comment]
Sorry but  ASSET_URL  doesn't exists in my .env

**Comment by karandatwani92** [comment]
Ok! We must ensure the `APP_URL` in your .env file is correctly pointing to the URL you use to access your application in the browser, for example http:127.0.0.1:8000 or http://something.test

please set that and try again.

**Comment by dauvray** [comment]
yes APP_URL is ok.


![MicrosoftTeams-image (1)](https://github.com/Laravel-Backpack/basset/assets/3491828/70b19a62-fa91-4137-a662-529d74cebf0d)

Only this 3 files fails. i will reinstall new project but it's it's annoying.

**Comment by dauvray** [comment]
finally I reinstalled a project and everything works, I don't understand what could have happened.

**Comment by karandatwani92** [comment]
@dauvray Thanks for confirming. I was also unable to think of the cause.
I'm glad you have it solved. Let me know if you find the cause; it may help others. Thanks

**Comment by dauvray** [comment]
Hello,

I come back with this bug.
It sometimes happens that when I make updates, the URL problem comes back.

I get this type on some URLs:
https://domain.fr/var/www/laravel-project/vendor/backpack/crud/src/resources/assets/css/common.css?f811ef3ab2df

instead of:
https://domain.fr/storage/basset/vendor/backpack/crud/src/resources/assets/js/common.css?f811ef3ab2df

So i checked BassetManager and i can see on line 160:
` if (! str_starts_with($asset, base_path()) && ! Str::isUrl($asset)) { ... }`
 
As we can see, there is a management of the character string to ensure that it does not start with base_path()

But in my case the character string starts with base_path() and there is nothing that manages my case.

So on line 223, i change :
` $output && $this->output->write($asset, $attributes);`
 
 with:
` $output && $this->output->write('/storage/'.$path, $attributes);`
 
 This solves my problem.
 Maybe I'm doing something wrong but I can't see what.
 
when i dump(($asset) , i cleary see that base_path() is in the string.
