### ISSUE TITLE
Laravel Backpack (basset) not working in docker with nginx

### ISSUE THREAD

**Issue by IlyaBuldakov** [Laravel-Backpack/basset#130]
I use laravel backpack and everything works when I start the server using `php artisan serve`, and then use the admin panel at `localhost:8000/admin`.

But as soon as I run docker(nginx + php fpm (here is backpack) + mysql) it stops working!

Okay, you tell me that basset is trying to use a local path and it is. My next step is to replace APP_ENV=local with APP_ENV=production (yes, that's exactly what I need). This way I achieve that backpack finds all the necessary files, but the page is displayed WITHOUT STYLES and other resources. Here is screenshots for case "APP_ENV=production, APP_URL=http://nginx"

![image](https://github.com/Laravel-Backpack/basset/assets/26491536/17289481-94ac-434f-8777-b411311aa9a8)
![image](https://github.com/Laravel-Backpack/basset/assets/26491536/84f96015-fdd0-4fb4-afc6-fc6f7d5ec559)
![image](https://github.com/Laravel-Backpack/basset/assets/26491536/f864c9ec-a212-4e24-82fd-cb056b71e4fa)

Here is my nginx.conf: 

`events {

}
http {
server {
        listen 80;
        server_name localhost;
        root  /var/www/next/public;

        index index.php;

        location ~* \.(jpg|jpeg|gif|css|png|js|ico|html)$ {
                access_log off;
                expires max;
                log_not_found off;
        }

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~* \.php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
                deny all;
        }
}
}`

and here is my docker-compose.yml

`
version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ../:/var/www/next:cache
            -   type: bind
                source: nginx.conf
                target: /etc/nginx/nginx.conf
        depends_on:
            - php-fpm
        networks:
            - next
    php-fpm:
        build: .
        volumes:
            - ../:/var/www/next:cache
            - ../docker/php.ini-development:/usr/local/etc/php/php.ini-development
        networks:
            - next
        depends_on:
            - db
    db:
        image: mysql
        ports:
            - 3306:3306
        networks:
            - next
        environment:
            MYSQL_ROOT_PASSWORD: root
networks:
    next:
        driver: bridge
`

I've been doing this for the 3rd day and I really need help :(
Thanks everyone

**Comment by pxpm** [comment]
I believe this is fixed in https://github.com/Laravel-Backpack/CRUD/issues/5526

Please re-open if I am wrong and we can have a look at it again 🙏

**Comment by tamert** [comment]
yes already some issue to me

![Ekran Resmi 2024-12-11 00 07 51](https://github.com/user-attachments/assets/ad3d87eb-bc6b-42ac-a6da-d564ad70f4aa)
