### ISSUE TITLE
Google Places API cache file broken?

### ISSUE THREAD

**Issue by nrodriguezm** [Laravel-Backpack/basset#132]
For some reason only the following google places file appears broken and breaks 'address_google' field. 
Browser console shows the following message:

> Uncaught SyntaxError: expected expression, got '<'
![image](https://github.com/Laravel-Backpack/basset/assets/4943349/64fd89cc-e868-40e3-9e49-21f8f06d5d34)

Changing APP_ENV to "local" removes the error and 'address_google' field works again as the JS file is downloaded:
![image](https://github.com/Laravel-Backpack/basset/assets/4943349/f218a18b-dd6e-4259-91a7-45b9537cd94b)

When inspecting the cache file on Forge server:

> vim storage/app/public/basset/google_places_api_script-03d2684f.js

It contains a single line:
> </script>

Already tried clearing cache and config, both with composer and basset commands.

Using:
backpack/basset                    1.3.4 
backpack/crud                      6.7.15 
backpack/theme-coreuiv4            1.1.1  

I am at a loss here, any help is very appreciated!

**Comment by pxpm** [comment]
Thanks for the report @nrodriguezm 

I will investigate it asap, it looks like a bug, I need to confirm if it actually is. 

Would you mind posting `storage/app/public/basset/google_places_api_script-03d2684f.js` content, so I can compare with my own output ? **(please make sure no API key is in that file before posting it here)**

Cheers

**Comment by pxpm** [comment]
fixed by #134

**Comment by pxpm** [comment]
Thanks again for the report @nrodriguezm 🙏 

The fix had been merged. 

Please run a composer update to get the updated versions 👍 

Cheers
