### ISSUE TITLE
Basset is Caching an Old Version

### ISSUE THREAD

**Issue by zachweix** [Laravel-Backpack/basset#133]
I updated to the latest version of Backpack Pro and Filemanager in order to be able to use ckeditor with the elfinder. On dev everything works fine, but on production, even after running `php artisan basset:fresh` it seems that an older version of the ckeditor cdn was cached (I think that the cachebusting string wasn't changed). I compared by temporarily switching the env to local, where everything worked fine, but when I switched back to production it stopped working. I looked at the source code of the basset cdn and the cdn itself and they gave different code. I'm not sure if this is a bug or if I'm missing somewhere to update the basset info

**Comment by jcastroa87** [comment]
Hello @zachweix 

Did you try cleaning fully the cache

```
php artisan optimize:clear
php artisan basset:clear
php artisan basset:cache
php artisan optimize
```

Check too if storage has correct permissions.
```
sudo chown -R $USER:www-data storage
sudo chmod -R 775 storage
```


And if nothing result, you can try to create again symlink.
```
php artisan storage:unlink
php artisan storage:link
```

Let me know if thats work for you.

Cheers.

**Comment by zachweix** [comment]
I'm not sure what did it, but `sudo chmod -R 775 storage` actually didn't work, because then the cached Backpack files failed to be created, so I changed it to 777 and now it works 🤷
