### ISSUE TITLE
Change folder name?

### ISSUE THREAD

**Issue by sidewaysglance** [Laravel-Backpack/basset#135]
Hi there

Great package, thank you. 

I aim to prevent external third parties from learning what type of system we are running on, and having the name `basset` in the source code is a giveaway. Would it be possible to instead of doing:

`<script src="https://example.com/storage/basset/js.pusher.com/7.0/pusher.min.js" defer></script>`

could we do something like:

`<script src="https://example.com/storage/cUsToMiSedlOcaTioN/js.pusher.com/7.0/pusher.min.js" defer></script>`

?

**Comment by pxpm** [comment]
Hey @sidewaysglance sure, just config the path: https://github.com/Laravel-Backpack/basset/blob/ffa775cab74d960bcbfa66741b1c88607680c45d/src/config/backpack/basset.php#L12

Follow the readme on how to publish the config to your application. 

Closing this as I don't think there is a bug here, if you find it has a bug, please re-open I may be wrong. 👍 

Cheers
