### ISSUE TITLE
Multiple Domains Causes Issues

### ISSUE THREAD

**Issue by zachweix** [Laravel-Backpack/basset#139]
Not sure how to give code to explain. I basically have multiple domains pointing to the same codebase (each one has a different database). The first domain loads fine, but then all future ones will not work. I get a message like this:
>Access to font at 'http://sub1.example.com/storage/basset/cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/fonts/la-solid-900.woff2' from origin 'http://subdomain.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

In theory I could just allow access, but then all other tenants will see that tenant's name in their network requests. I got around this by manually changing my config to make basset always think I am in dev mode, but I can't figure out how to get it to work that each one will load the proper url. Since the app url is changed on the fly, I can't just use the env value. I realize this might be outside the scope of the project, but in theory it's just a matter of how can I tell it what "main url" to use instead of forcing it to use the app url
(I'm using https://tenancyforlaravel.com/docs/v3/introduction/)

**Comment by pxpm** [comment]
Hey @zachweix thanks for the question.

We use by default the "public" disk. If you are using it, you can probably use a `Middleware` to change the disk url "on the fly". 

The default URL is generated from the `env()` value of `APP_URL`:

https://github.com/laravel/laravel/blob/c9c8fb9ee73266b2bb4183603b553b2ee9030252/config/filesystems.php#L43

In a middleware, you can probably do: `config(['filesystems.disks.public.url' => config('app.url').'/storage'])` assuming `config('app.url')` already has the changed value. If not you can probably get it from the tenant identification. 

Let me know if that helps. 

Cheers 👍

**Comment by zachweix** [comment]
Problem with this is that the BassetServiceProvider loads before middleware. However, all you need to do is to reload basset, so (after too much time testing), I got this to work:

```
config(['filesystems.disks.public.url' => url('storage')]);
app()->scoped('basset', fn () => new \Backpack\Basset\BassetManager());
```

**Comment by zachweix** [comment]
Actually, that wasn't good enough for caching urls, so I did the following:

```
$filesystems = config('filesystems');

config(['filesystems.disks.local.root' => $filesystems['disks']['root']['root'] . '/storage/app']);
config(['filesystems.disks.public.root' => $filesystems['disks']['root']['root'] . '/storage/app/public']);
config(['filesystems.disks.public.url' => url('storage')]);

app()->scoped('basset', fn () => new \Backpack\Basset\BassetManager());
config(['filesystems' => $filesystems]);
```

**Comment by pxpm** [comment]
Hey @zachweix thanks for providing the solution. 

I think we can make developers in your situation life easier if we had a `setDisk()` on `BassetManager` right ? So that users can do `Basset::setDisk(FilesystemAdapter|string $disk)` ? 

Wanna contribute a PR for that ? 

Cheers

**Comment by zachweix** [comment]
It ended up not helping anyway and it is such an obscure case, I don't know if it is worth it to have that just for my purpose, especially since documenting that could potentially cause more confusion than help
