### ISSUE TITLE
Provide a way for 3rd party packages to add internalization paths

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#15]
For example we have 3 themes:
```
        "backpack/theme-coreuiv2": "dev-main",
        "backpack/theme-coreuiv4": "dev-main",
        "backpack/theme-tabler": "dev-main"
```

All 3 would like to do something in their ServiceProvider's `boot()` method:

```
BassetManager::addPath()
```

Also, CRUD and PRO would need to do the same thing, in their service providers.

**Comment by promatik** [comment]
Moving to https://github.com/Laravel-Backpack/basset/pull/24 🙌
