### ISSUE TITLE
DEV mode - config to disable internalization

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#16]
As a developer, you sometimes need Basset to do nothing:
- CDNs - use directly
- local bassets - internalize even if already internalized
- basset blocks - internalize even if already internalized
- basset directory - internalize even if already internalized
- local basset archive - internalize even if already internalized
- online basset archive - do nothing differently (internalize only if not already internalized)

**Comment by promatik** [comment]
Moving to https://github.com/Laravel-Backpack/basset/pull/23 🙌
