### ISSUE TITLE
Naming: `getPath()` and `getUrl()`

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#21]
I noticed in https://github.com/Laravel-Backpack/basset/pull/20 that we have:

```php
Basset::getAssetPath()
Basset::getAssetUrl()
```

Wouldn't it make more sense to have
```php
Basset::getPath()
Basset::getUrl()
```

I mean... `Basset` reads like asset, right? Everything you do using `Basset::` is for one asset.

**Comment by promatik** [comment]
Yes, I agree!
Will change it 👌

**Comment by promatik** [comment]
Fixed by https://github.com/Laravel-Backpack/basset/pull/22.
