### ISSUE TITLE
Branding - do we use Singular or Plural?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#32]
Should we focus on using the term `bassets` or `basset`?

**A. Bassets (plural)**
- could read like "_backpack assets_" or "_backed up assets_"
- directory would also be in plural (`storage/app/public/bassets`) which makes sense since it holds bassets
- cache file would also be in plural (`storage/app/public/bassets/.bassets`) which makes sense since it holds bassets 

**B. Basset (singular)**
- could read like a pet ([basset hound](https://ro.wikipedia.org/wiki/Basset_Hound))
- we could rename the `php artisan basset:internalize` to `php artisan basset:fetch` so that you "play fetch" with Basset

**Comment by pxpm** [comment]
I don't like so many "s"s in `bassets` s s.s .s.s.s .s .s. .ss.s. s. s.s .!

But `basset` in the context of assets look even worst! 

I go for **a)**!

**Comment by promatik** [comment]
I understand both...

As I've said before, I like **B.** — **Basset** for the name of the package, and for naming stuff like;
1) the `.basset` file, that holds a list of **bassets**, but may have more stuff in the future.
2) the `storage/.../basset` folder, that holds everything related with the **Basset** package — all the **bassets** and the cache file, and may have more stuff in future 🤷‍♂️

I think this is the most "future proff" way ...
But I'm ready for making the changes ✌️😅

**Comment by pxpm** [comment]
> I understand both...
> 
> As I've said before, I like **B.** — **Basset** for the name of the package, and for naming stuff like;
> 
> 1. the `.basset` file, that holds a list of **bassets**, but may have more stuff in the future.
> 2. the `storage/.../basset` folder, that holds everything related with the **Basset** package — all the **bassets** and the cache file, and may have more stuff in future 🤷‍♂️
> 
> I think this is the most "future proff" way ... But I'm ready for making the changes ✌️😅

You guys probably know better the direction the package can take in future, so I trust your judgment. 
I was just waiting for a `composer update` to finish and decided to shime in with my uninformed response 🙃

**Comment by promatik** [comment]
@pxpm your answer is more than valid 😅
I think Cristian is on your side ahaha and I have my doubts too 🤷‍♂️ I just wanted to let the pros of B written too 👌

**Comment by tabacitu** [comment]
Fuck it, we're keeping Basset. We have bigger problems to worry about.
