### ISSUE TITLE
CSP (content security policy) nonce support

### ISSUE THREAD

**Issue by GOG-Games-com** [Laravel-Backpack/basset#35]
Hi, I am using [spatie/laravel-csp ](https://github.com/spatie/laravel-csp)to set CSP headers and nonce values are needed for script and style for my website. Is there a way to have support for this? Similar to this: https://github.com/livewire/livewire/issues/650

The styles and scripts are blocked when loading the admin panel so nothing loads as it requires the JS to load.

Thank you.

**Comment by promatik** [comment]
Fixed by https://github.com/Laravel-Backpack/basset/pull/47.
