### ISSUE TITLE
Document DEV_MODE & maybe make it default on localhost

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/basset#38]
https://github.com/Laravel-Backpack/basset/blob/cf6a3b3a13d0b66b272242068d1df765209dd5d7/src/config/backpack/basset.php#LL5C24-L5C39

We need to document this super important bit!

**Comment by tabacitu** [comment]
I'm wondering... should we make `BASSET_DEV_MODE` default to `true` on localhost? 🤷‍♂️ Isn't this something most devs will need to do, anyway?

**Comment by promatik** [comment]
I'll close this one in favor of, #54 and #55 👌
