### ISSUE TITLE
Sometimes a double slash gets added

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/basset#40]
I can't pinpoint exactly how/when/why but I noticed sometimes the bassets have a double slash. 

For example in our demo, using the CoreUIv2 theme, I get the following error: 

![image](https://github.com/Laravel-Backpack/basset/assets/7188159/c7be6c30-257c-4b5a-9cc0-69ad3bbe475c)

While checking the returned content from a `Inline Create modal endpoint` I also found one of those:

![image](https://github.com/Laravel-Backpack/basset/assets/7188159/52def690-c3bf-44ba-9b0c-ff2412abfc21)

You can test the last one in our demo in `Monsters -> Relationship -> BelongsToMany + Ajax + Inline Create`. 

Ping me if I can help you debugging something else.

**Comment by tabacitu** [comment]
Heads-up - we have an online demo for v6 now, so we can point to specific URLs when we can prove problems in our demo. In this case it would be: https://demo-v6.backpackforlaravel.com/admin/monster/create#relationship

Howeeeever. On that page I get a completely different error now 🤦‍♂️
<img width="1512" alt="CleanShot 2023-05-26 at 11 46 03@2x" src="https://github.com/Laravel-Backpack/basset/assets/1032474/9da57b11-fab7-4eeb-8861-70bd89baf368">

**Comment by pxpm** [comment]
I think that's a separate issue @tabacitu 

I've identified it too, but I think it's related with the update to CKEditor v5, not specifically the theme or assets.

**Comment by tabacitu** [comment]
Didn't get this any more, for a while now, so I'm going to close it. If anybody gets this please provide more information and re-open.
