### ISSUE TITLE
Maybe we rename the `internalize` command?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#41]
It feels a little odd to me to have `php artisan basset:internalize`, it seems unlike any other default Laravel command. Considering [other artisan commands](https://artisan.page/), how about we do...

```bash
php artisan basset:clear // done
php artisan basset:cache // instead of internalize
```

That way it would be similar to:
```bash
// views
php artisan view:cache
php artisan view:clear

// cache
php artisan cache:clear

// events
php artisan event:cache
php artisan event:clear

// routes
php artisan route:cache
php artisan route:clear
php artisan route:list
```

**Comment by tabacitu** [comment]
What do you think @promatik ?

**Comment by promatik** [comment]
Yup 👌
I agree, internalize was a fancy term we decided to have, but cache is much easier for developers to memorize.
I actually don't see any reason to have `internalize` 🤷‍♂️

PR is open at https://github.com/Laravel-Backpack/basset/pull/45 👌
