### ISSUE TITLE
Command to run both `clear` and `internalize`

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#42]
I find most of the time that's what I want to do:
```
php artisan basset:clear
php artisan basset:internalize
```

So why not create a command that does both? How about...
- (1) `php artisan basset:fresh`
- (2) `php artisan basset:refresh`
- (3) `php artisan basset:run`

I prefer 1 or 2. @promatik what do you think?

**Comment by promatik** [comment]
I vote for (1) 👌

That way we have;

```cmd
php artisan basset:cache
php artisan basset:clear
php artisan basset:fresh
```

PR is here; https://github.com/Laravel-Backpack/basset/pull/48
