### ISSUE TITLE
[DX] Why do we ABSOLUTELY need to run `php artisan storage:link`?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#43]
I mean... it's recommended, sure... so that bassets cached in `storage/app/public` not `public`. But... if `php artisan storage:link` wasn't done... why don't we cache the assets in `public` directly? 👀🤷‍♂️ I mean... 

(1) If the dev hasn't done `php artisan storage:link`... that's _probably_ what they want, right?
(2) Aren't there use cases where `php artisan storage:link` cannot be run? For example on shared hosting with cPanel, where SSH access is disabled, so they don't have any terminal access? Does Backpack work on those in the first place?! 🤷‍♂️ haven't tried in years;
(3) Isn't caching stuff in `public` better than Basset completely failing to work, if `php artisan storage:link` hasn't been run?

What do you think @promatik ? Can we easily do this? SHOULD WE do this?

**Comment by promatik** [comment]
@tabacitu we use the public disk by default, in a new Laravel project that is pointing to storage;
https://github.com/laravel/laravel/blob/10.x/config/filesystems.php#L39-L45

If the user wants to use the public folder it's as easy as to;

1) Change the filesystem config with the public disk pointing to public instead of storage.
**OR**
2) Change basset config;

```diff
...
    // disk and path where to store bassets
-    'disk' => 'public',
+    'disk' => 'uploads',
    'path' => 'basset',
...

Everything will work accordingly.

This is the correct behaviour to be expected.
BUT, we may prevent developers frustration by being more explicit in the README and/or add some try catch on basset to explain storage:link was not run, and pointing to either run it or change the disk.

Let me know what do you think @tabacitu 👌

**Comment by tabacitu** [comment]
Let's keep using the storage link. No way around it.

But let's also: 
- [ ] create a `php artisan basset:install` command, that creates the symlink AND adds the symlink to composer.json's `post-install` hook;
- [ ] improve the documentation, to tell people they also need to create the symlinks in staging, dev, production servers;
- [ ] also add this to `php artisan backpack:install` command (we at least make it easier there);

**Comment by promatik** [comment]
`php artisan basset:install`
https://github.com/Laravel-Backpack/basset/pull/51
