### ISSUE TITLE
Feature request: Add autoloaded theme styles to basset internalize command

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/basset#61]
In the Backpack theming configuration files, like `ui.php` and `theme-XXX.php`, it is possible to add css styles that are statically loaded on all pages of the admin panel. These styles are dynamically added to load as bassets at runtime, but therefore are not detected within the views when running the internalize command and thus not cached yet.

It would be nice to have these assets also processed when running the internalize command, to have less operations when the first request lands.

**Comment by tabacitu** [comment]
Hmm... interesting. Thanks @jnoordsij

**Comment by promatik** [comment]
This ons was "covered" some time ago when we added this code on both `scripts.blade.php` and `styles.blade.php`:

![image](https://github.com/Laravel-Backpack/basset/assets/1838187/b7b41792-32ac-44a7-94be-49b4a8f4e9b3)

It will load the scripts and styles with basset 👌
