### ISSUE TITLE
Feature request: allow adding compressed version of bassets

### ISSUE THREAD

**Issue by jnoordsij** [Laravel-Backpack/basset#63]
Currently bassets are saved to the disk as regular (uncompressed) files. However, most webservers use compression (e.g. gzip or brotli) when sending assets to clients. Compression is then done by the webserver at runtime, which uses a bit of CPU and therefore is usually not done at the highest compression levels.

It would be a nice addition to have basset also generate a compressed version, which is saved alongside the regular file, so that the webserver can serve a precompressed file, which saves CPU and can be compressed at higher levels.

An example of such an implementation (for gzip) can be found in the Drupal core: https://github.com/drupal/core/blob/9243e0bb1b3001007594f7e9b0ab07712a5db447/lib/Drupal/Core/Asset/AssetDumper.php. Support for brotli compressed files for Drupal is part of an issue that can be found at https://www.drupal.org/project/drupal/issues/3184242.

This should probably be user-configurable, to prevent lots of additional overhead on (first) requests for users who are not interested, e.g.  because their webserver is not configured to check for precompressed files.

**Comment by tabacitu** [comment]
Hey @jnoordsij - that would be cool indeed. 

But I'd say it's out of scope for this package. I would make us go deeper than we planned - this package aims to solve the asset management problem, not being an all-in-one solution for serving assets efficiently. I think the server configuration is a much better place to do that. And when done efficiently (combined with caching), it takes little to no CPU afaik.

So... I may be wrong... but I'm going to have to say "no" to this one. I'm wrong all the time though 😅 So if you (or anybody else that comes here) disagrees with me please let me know and we'll reopen.

Cheers!

**Comment by jnoordsij** [comment]
@tabacitu I totally understand, it's a bit of a niche improvement that I just thought would be a nice thing to add and hence suggested, just so that if anyone comes around and likes the suggestion they can try and pick it up and implement it. But since it will probably require quite a bit of coding and maintenance, I do understand not doing this.

Another note: now that I think of it, what you could somewhat easily is fire some kind of custom (Laravel) event containing the file path and content whenever a basset is written to the disk, which would allow people to listen to the event and easily add any additional logic they want to it. That would allow someone to create the idea of this issue as some sort of add-on that you would not have to maintain here, but still could be profitable. Still just a wild suggestion though ;)

**Comment by jnoordsij** [comment]
Also before I forget to mention this anywhere: I think Basset really is a great addition to how assets are managed in Backpack and really will help a lot of people with more stable and manageable assets, so my compliments to you and the rest of the team for that!

**Comment by tabacitu** [comment]
> Another note: now that I think of it, what you could somewhat easily is fire some kind of custom (Laravel) event containing the file path and content whenever a basset is written to the disk, which would allow people to listen to the event and easily add any additional logic they want to it. That would allow someone to create the idea of this issue as some sort of add-on that you would not have to maintain here, but still could be profitable. Still just a wild suggestion though ;)

That is a GREAT idea. So that if people want to do custom stuff, there's a way for them to do so without touching the Basset core. I LOVE THIS! ❤️ I've added https://github.com/Laravel-Backpack/basset/issues/65 to talk about this. Brilliant! 🤦‍♂️

> I think Basset really is a great addition to how assets are managed in Backpack and really will help a lot of people with more stable and manageable assets, so my compliments to you and the rest of the team for that!

Awww. Thank you for the kind words @jnoordsij 🙏 All credit goes to @promatik - he's done everything around here, from prototype to v1. I was just the idea man and tester 😀
