### ISSUE TITLE
Feature request: trigger events

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#65]
This package is Laravel-specific. So Events are present. Why don't we trigger some events during the Basset lifecycle, so that... if people need to do custom stuff... they can easily do that? 

This idea belongs to @jnoordsij - in https://github.com/Laravel-Backpack/basset/issues/63 he wanted to compress the files. Which is a reasonable need, but not something this package should be concerned doing. Right now, there's not much you can do to achieve that. What if instead of saying "_no_" we can always say "_yes, here's the event system, do it in your project or in a package_"? I think that would kick ass!!

@promatik what do you think? What would an event system looks like - where are the touchpoints where it makes sense to add events?

**Comment by promatik** [comment]
Wow!
Nice idea @jnoordsij! Please keep them coming 👌
Totally agree with this one.

**Comment by promatik** [comment]
Moving to https://github.com/Laravel-Backpack/basset/pull/92 👌
