### ISSUE TITLE
More easy to use without storage:link

### ISSUE THREAD

**Issue by adriallongarriu** [Laravel-Backpack/basset#67]
My local dev enviroment is a Windows with Homestead i can't have symlink. 
In my case i have a project  with v5 and wanted to upgrade to v6. 
I flollow the [Upgrade Guide](https://backpackforlaravel.com/docs/6.x/upgrade-guide)  an in the Step 3.2.  you need to use the comand `php artisan backpack:install` this comand is using `php artisan basset:install` this comand don't have option or config to not create symlink. 
Error: ` symlink(): Input/output error`
![image](https://github.com/Laravel-Backpack/basset/assets/20278289/b95559b5-9a33-46d2-83da-919fa512bc80)

I look at #43 and changed my disk but the error persist. 
Plus the Basset config says it is disabled by default but keep trying to create the symlink. 
![image](https://github.com/Laravel-Backpack/basset/assets/20278289/4088df5f-2ea5-4cf1-999f-628bf799d9f0)
> Basset is disabled by default on local environment (APP_ENV=local), if you want to change it please set BASSET_DEV_MODE=false on the env file.

I debug the comand  `basset:install` and see if you already have the folder storage the symlink will not be created.
https://github.com/Laravel-Backpack/basset/blob/8a7e2ded65420ef6162171c6b86eb7b385dadd25/src/Console/Commands/BassetInstall.php#L54C1-L66C6
I created the folder and I was able to continue with the installation.

### **Conclusion**
I will prefer this infromation be more accessible and a clear way to do it. In the readme or in the documentation you have symlink use this config or  if you can't have symlink do this. But not limit or focre to have symlink.

**Comment by tabacitu** [comment]
Hmm fair enough. We shouldn't _force_ it is it's not _absolutely necessary_. At the very least we should fail gracefully. @promatik what do you think is the best course of action here?

**Comment by promatik** [comment]
We have two solutions IMO;
1) Turn it into a question 🤷‍♂️
- cons: we bother everyone with the question
- pros: this issue would be solved easily for this cases

2) Have a config `'synlink' => true`. In this specific cases devs would need to turn it false to avoid the error.
- pros: we don't bother everyone
- cons: devs with this issue will need to search how to solve it, and change the config (it's not a direct fix).

**Comment by promatik** [comment]
Hey @adriallongarriu, I'm glad to say we found a solution 🙌

We no longer enforce the creation of the symlink, we try it, but it won't fail and stop the installation on errors.

We also added a `php artisan basset:check` command that will help developers to check if basset is working, and if not, to understand why.

In your case, since you can't create symlinks you'll need your own disk on public folder (please make sure the files are publicly accessible).

Once #72 is merged, please feel free to test it. If you still have any issue please let us know 🙌
