### ISSUE TITLE
`basset(base_path(''))` not working on Vapor?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#71]
@maulsea said in [this comment](https://github.com/Laravel-Backpack/basset/pull/58#issuecomment-1648286096):

> @promatik Looks like the @basset(base_path('...') references are not working for me in the vapor environment. In other words, basset is not uploading those assets to s3. Is there a way to disable Basset for them? We are okay without optimization there.

**Comment by tabacitu** [comment]
@promatik is that possible to overcome? How? Why?

**Comment by promatik** [comment]
I'm quite sure https://github.com/Laravel-Backpack/basset/pull/72 will point the miss configurations for @maulsea 👌

@maulsea if #72 doesn't fix it for you, please let me know and let's reopen this issue 🙌
