### ISSUE TITLE
Why does the outputted script type have a hash? 

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#77]
I noticed on https://demo.backpackforlaravel.com/admin/login that the outputted scripts look like this:

<img width="1300" alt="CleanShot 2023-08-02 at 15 57 46@2x" src="https://github.com/Laravel-Backpack/basset/assets/1032474/9e1ea275-a73e-4a2b-a08b-9b8c8043c5da">

@promatik why is the `type="2559f5b228d9cebdf685edf1-text/javascript"`? Is this intentional or by mistake?

**Comment by pxpm** [comment]
It seems to me to be a CF thing.

**Comment by promatik** [comment]
Yes, it looks like CloudFlare is doing some nasty stuff there 😅
It's the Cloud Flare rocket loader who's adding that there;
https://community.cloudflare.com/t/script-tags-type-attribute-hash-prepended/145679

**Comment by tabacitu** [comment]
Pfiew! Ok fine thanks guys!
