### ISSUE TITLE
Possible bug on windows development (WAMP, Laragon)

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/basset#81]
While debugging a problem I was having with themes, I decided to work from home and test it out on windows thinking I wouldn't have to worry about permissions on directories! Instead I found this potential bug:

If you're developing on windows (without WSL as that environment works like linux) then you may run into problems with initialising basset. It will report that it's setup but due to the way windows works, symbolic links won't be created - there won't be a reference to the storage directory in public/

Hopefully this can be added to the docs until laravel/symfony/someone come up with a better way for windows dev boxes!

**Comment by pxpm** [comment]
Hello @fronbow 

I use Laragon for development on windows and previously used wamp too. I neved had issues creating symlinks in folders ?

![image](https://github.com/Laravel-Backpack/basset/assets/7188159/2be47cc6-158c-4de3-b182-1354844da356)

What issue are you getting ? 

What's the output of `php artisan backpack:version && php artisan basset:check` ?

**Comment by promatik** [comment]
Hi @fronbow!

Basset was +95% done on Windows 😅
I've been using it on windows and everything seems to work fine, symlinks also work on windows and I'm using windows terminal, **not WSL**.

---

Anyway, in case you cannot use symlinks, you can always setup a different basset disk to your public folder 👌
https://github.com/Laravel-Backpack/basset#storage-symlink

**Comment by fronbow** [comment]
Wow, that's awesome. I was having trouble with symlinks not showing in my setup. It didn't matter what I tried, they just wouldn't show up. I'm not on it atm, but basset:check was giving cUrl errors otherwise it was saying that everything else was fine.

**Comment by tabacitu** [comment]
@fronbow can you please give us a screenshot of you getting the curl error?

**Comment by fronbow** [comment]
Unfortunately not, although using the power of google search history I can see that the error I was getting was "Laravel CURL Error 60: SSL Certificate Problem: Unable To Get Local Issuer Certificate". If I get near my home machine then I'll see if it still exists - Win10 has been trying to update to Win11 all week!!!

**Comment by promatik** [comment]
Hi @fronbow, I believe this issue will be solved when https://github.com/Laravel-Backpack/basset/issues/95 gets merged 🙌

It will solve the cURL error on local development, I'll close this one for now.
