### ISSUE TITLE
Basset needs a better Readme.

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/basset#82]
While I wrote **Basset** article. I put only what I got only a few things available in readme.

But when I fixed a Bug https://github.com/Laravel-Backpack/CRUD/pull/5277
I got to know **Basset offers a Facade & many functions too.** which are not currently in the readme

My suggestion is to have them listed on the readme. we must  **mention facade** and **LIST**
- Available functions with short descriptions
- Available commands with short descriptions
- Available blade directives with short descriptions

It would be more clear for the user to have things in place, rather than jumping through text to know more.

After this, I need to amend those details in the article as well...before publishing it.

**Comment by tabacitu** [comment]
Totally agree. Not sure how important the Facade is to document... I doubt many people would be using it. But for advanced use I guess it would be helpful yes.

**Comment by tabacitu** [comment]
@karandatwani92 heads-up, I've just refactored the Functionalities section of the README into "Usage", where I break down the main API the new `basset()` helper and all our previous Blade directives and commands.

I think this will tick all your boxes except for the "functions" part. I think you expected us to also define the BassetManager public functions? If so... why did you ever need that? Will the new `basset()` helper cover that need? I'd rather not document the "inner works" if not absolutely needed.

**Comment by tabacitu** [comment]
Tbh I think the README is good-enough as it is. If you feel something is missing, please reopen this. If not, let's move forward 💪
