### ISSUE TITLE
[Feature Request] Helper function?

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#83]
We got [some feedback](https://laracasts.com/discuss/channels/laravel/new-way-to-load-css-js-assets-basset-what-do-you-think?page=1&replyId=902119) that a helper function could be useful. And indeed it'd be easy to create a `basset()` function that returns... what? That's the question. What would it return? 

It could be:
- (a) the path to the internalized assed, so you can do `<script src="{{ basset('https://path/to/file.js') }}">`
- (b) the entire output, as a string, so you can do `{{ basset('https://path/to/file.js') }}` instead of `@basset('https://path/to/file.js')`
- (c) an object that implements Stringable... so if you echo it it's the same thing as (a) above... but you could also do other stuff to it like... I don't know 😅

So... probably (a) right? @promatik what do you think?

**Comment by tabacitu** [comment]
Just realized if we do (a) or (c)... this would make `basset()` a drop-in replacement for Laravel's `asset()` helper. Which I think is great.

So you'd have two ways of using Basset:
- `@basset()` to replace your `<script src="https://path/to/file.js">`
- `basset('https://path/to/file.js')` to replace your `asset('https://path/to/file.js')`

🤯

**Comment by pxpm** [comment]
Guess the directive would be a wrapper around `Basset::getUrl()` then. 👍

**Comment by tabacitu** [comment]
🤷‍♂️ does that work if the asset hasn't been internalized yet? I don't think so. @promatik will know more, but I think it'd be more like:

```php
public function basset(string $asset) {
    $status = Basset::basset($asset);

    // TODO: Maybe do some checks if the asset hasn't been internalized? I don't know.

    return Basset::getUrl($asset);
}
```

But in any case, yes, that would be the return, `Basset::getUrl()`

**Comment by promatik** [comment]
Hey @tabacitu let's move this to #85 👌
I've made some changes there too.
