### ISSUE TITLE
[Feature Request] Support for SVGs and images

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/basset#84]
What if you want to [internalize an image or SVG from a third-party website](https://laracasts.com/discuss/channels/laravel/new-way-to-load-css-js-assets-basset-what-do-you-think?page=1&replyId=902124)? Wouldn't it be cool if we could do:

```
@basset('https://path/to/file.svg')
```

and it would output

```
<img src="https://local.app/path/to/internalized/file.svg">
```

Of course... we'd have to do that for all image types... right? 👀 What do you think @promatik ? Worth doing or not?

**Comment by tabacitu** [comment]
Maybe not as helpful to load images from CDNs. But you might want to load an `img` from a non-public directory, if you're a package, right? And not ask devs to publish their assets in order to get them.

**Comment by tabacitu** [comment]
@promatik  mentioned this might open Pandora's box. If we start supporting image filetypes... what's next? And where do we stop? And he might be right. 

After all, if we do https://github.com/Laravel-Backpack/basset/issues/83 there will be a way for ALL filetypes to use Basset... by defining the HTML element themselves and using the `basset()` helper alone. So that would be a solution too, I guess.

But let's entertain the idea a little bit longer. Let's crunch the numbers, see what's actually inside Pandora's box 😅

---

Here's a list of HTML elements that are commonly used to load external files, along with the attributes they use:

| HTML Element          | Purpose                              | Attribute | Basset support |
|-----------------------|--------------------------------------|-----------|-----------|
| \<script>             | Include external JavaScript files    | src       | ✅       |
| \<link>               | Include external stylesheets (CSS)   | href      | ✅       |
| \<img>                | Display images                       | src       | -       |
| \<iframe>             | Embed another HTML document          | src       | -       |
| \<audio>              | Embed audio content                  | src       | -       |
| \<video>              | Embed video content                  | src       | -       |
| \<source>             | Specify media sources                | src       | -       |
| \<object>             | Embed external resources             | data      | -       |
| \<embed>              | Embed external content               | src       | -       |
| \<track>              | Provide text tracks for media        | src       | -       |
| \<frame>              | Define frames within a frameset      | src       | -       |
| \<input> (type="image")| Image-based submit button for forms  | src       | -       |
| \<script> (type="module") | Load JavaScript modules           | src       | -       |

And here's a list of the most common file extensions used in web pages:

1. **.html**: HTML files, the backbone of web pages.
2. **.htm**: HTML files (alternative extension).
3. **.css**: Cascading Style Sheets files, used for styling and layout. ✅ already has basset support
4. **.js**: JavaScript files, used for client-side scripting and interactivity.  ✅ already has basset support
5. **.jsx**: JavaScript files with JSX syntax, often used in React applications.
6. **.ts**: TypeScript files, a superset of JavaScript with static typing.
7. **.tsx**: TypeScript files with JSX syntax.
8. **.php**: PHP files, though primarily server-side, they can contain mixed HTML and PHP code.
9. **.jpg** or **.jpeg**: JPEG image files, commonly used for images.
10. **.png**: Portable Network Graphics image files, commonly used for images with transparency.
11. **.gif**: Graphics Interchange Format image files, often used for animations or simple images.
12. **.svg**: Scalable Vector Graphics files, used for vector images and graphics.
13. **.ico**: Icon files, used for favicon and other icons.
14. **.woff**: Web Open Font Format files, used for web fonts.
15. **.woff2**: Web Open Font Format 2.0 files, a more compressed version of web fonts.
16. **.ttf**: TrueType Font files, another font format for web use.
17. **.otf**: OpenType Font files, a font format compatible with various platforms.
18. **.eot**: Embedded OpenType font files, an older format of web font.
19. **.json**: JSON (JavaScript Object Notation) files, used for data interchange.
20. **.xml**: Extensible Markup Language files, used for structured data.
21. **.csv**: Comma-separated values files, often used for data exchange.
22. **.mp4**: MPEG-4 video files, often used for video content on the web.
23. **.webm**: WebM video files, an open and royalty-free video format.
24. **.ogg**: Ogg multimedia container format, often used for audio and video.
25. **.mp3**: MPEG Audio Layer III files, commonly used for audio.
26. **.wav**: Waveform Audio File Format, used for high-quality audio.
27. **.avi**: Audio Video Interleave files, a multimedia container format.
28. **.pdf**: Portable Document Format files, used for documents and forms.
29. **.doc** or **.docx**: Microsoft Word document files.
30. **.xls** or **.xlsx**: Microsoft Excel spreadsheet files.
31. **.ppt** or **.pptx**: Microsoft PowerPoint presentation files.
32. **.zip**: Zip archive files, used for compression and packaging.
33. **.rar**: RAR archive files, another compression and packaging format.

Looks like A LOT, doesn't it? But on the other hand 😅 It wouldn't be _terribly difficult_ to continue making some assumptions based on the filetype, in order to offer support for more of them. Let's ask ourselves this... **What HTML element might a developer want, depending on filetype? If we are 100% sure they want an element... why not do it?**

So merging the two datasets above, with that question in mind, we have:
- .css: `<link>` ✅ done
- .js: `<script>` ✅ done
- .jpg or .jpeg or .png or .gif: `<img>` -  **🎰 maybe worth doing?**
- .ico: `<link>` (favicon)  -  **🎰 maybe worth doing?**
- .svg: `<img>` or `<source>`   -  **🎰 maybe worth doing as `<img>`?**
- .woff or .woff2 or .ttf or .otf or .eot: `<style>`, `<link>` -  **🎰 maybe worth doing as `<link>`?**
- .mp4 or .webm or .ogg or .avi: `<video>`, `<source>`, `<object>`  -  **🎰 maybe worth doing as `<video>`?**
- .mp3 or .wav: `<audio>`, `<source>`  -  **🎰 maybe worth doing as `<audio>`?**
- .json: `<script>`, `<link>` (for JSON data)  - ❌
- .xml: `<object>`, `<iframe>`, `<a>`  - ❌
- .csv: `<a>`, `<object>`, `<iframe>`  - ❌
- .pdf or .doc or .docx or .xls or .xlsx or .ppt or .pptx: `<a>`, `<object>`, `<iframe>`  - ❌
- .zip or .rar: `<a>`, `<object>`, `<iframe>`  - ❌
- .jsx or .ts or .tsx: `<script>` (when using frameworks like React or TypeScript) - ❌
- .php: `<iframe>`, `<object>`, `<a>` (when embedding PHP content) - ❌
- .html or .htm: `<iframe>`, `<object>`, `<a>` - ❌

Soo... the question is... _should we_ do it? 😅

PROs:
- we would support the most common 19 file extensions on the web... instead of just 2;

CONs:
- we would support 19 file extensions, not just 2; 😅

---

I don't know. Open to other opinions.

**Comment by fronbow** [comment]
Sounds awesome to me, though I would want maybe a config option of what file types to support as most of my hosts are a bit picky about bandwidth and storage, especially for audio and video!!
`iframes` could get a bit messy as basset would have to crawl the `iframe` looking for its' external resources that sometimes embed stuff using javascript.

**Comment by promatik** [comment]
Fixed by https://github.com/Laravel-Backpack/basset/pull/91 🙌
