### ISSUE TITLE
[Feature request] Minimise files on production?

### ISSUE THREAD

**Issue by fronbow** [Laravel-Backpack/basset#86]
Hi All

I've been contemplating adding this (https://github.com/matthiasmullie/minify) into the basset pipeline - it's in the back of my head for when I get a spare moment!
I've noticed there's quite a bit of overhead with the amount of files that get basset-ed so wondering whether there's any mileage in minimising the styles and scripts in a production environment, or maybe even adding a command switch to the basset command to force minimisation so the developer could do `@basset('https://cdn.com/path/to/file.js', 'minimise=true')` or somesuch.

I was also wondering if there's any mileage in concatenation - I seem to remember something like this in WordPress or drupal (can't remember which as it's been a while since I've been over their sides!!) where you could state when a script or style relied on another like jquery and they would be concatenated in a specific order - obviously not for all files, just the global stuff, but what's the general consensus?

Cheers

**Comment by tabacitu** [comment]
Hey @fronbow - this should be possible to do, as a dev, if we do https://github.com/Laravel-Backpack/basset/issues/86 - that idea came out of the same need. So let's move the conversation there.

But regarding your question... this might make sense if you have a lot of custom CSS and JS. But the CSS and JS Backpack uses is already minified. So the benefit would be minimal, if you ask me.
