### ISSUE TITLE
What is the reason some files from CDN are not imported?

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/basset#93]
Theme: tabler with backpack 6

![image](https://github.com/Laravel-Backpack/basset/assets/1268699/006cb8b7-eb3e-4db4-98ea-16c95a6f49ed)

Why we still have so many unpkg? should not be all downloaded from basset?

**Comment by karandatwani92** [comment]
Hey @realtebo Please update the tabler theme.  The latest version of the tabler-theme doesn't have this issue which we can verify from the demo:

![Screenshot 2023-09-01 at 1 11 51 PM](https://github.com/Laravel-Backpack/basset/assets/8214221/88cef5b9-aad9-4ac0-8fb7-b2c95c5510a9)

In case you published views to customize, check in `resources/views/vendor/backpack/theme-tabler`.

**Comment by pxpm** [comment]
Hey @realtebo it's also worth to check if you have basset enabled. 

Vendor files and non-public assets are always internalized to be served, even if you have basset disabled, otherwise they wouldn't work. 

The url assets are not internalized if basset is disabled. If not, everything should be internalized. 

Cheers

**Comment by realtebo** [comment]
Thanks, but we have same problem with a fresh install on a clean project.

Anyway we'll try. I'll tell you in a few day due to my holidays

How to upgrade tabler? 
I hoped it will be upgraded when upgrading backpack

[please document it]

We have nothing published and only 1-2 small blades ovverriden [buttons and filters]

**Comment by Mirko-Tebaldi** [comment]
Sorry, but same bug with latest version !

```
λ php artisan backpack:version                                                             
### PHP VERSION:                                                                           
PHP 8.2.8 (cli) (built: Jul  4 2023 15:53:15) (ZTS Visual C++ 2019 x64)                    
Copyright (c) The PHP Group                                                                
Zend Engine v4.2.8, Copyright (c) Zend Technologies                                        
                                                                                           
### LARAVEL VERSION:                                                                       
10.21.0.0                                                                                  
                                                                                           
### BACKPACK PACKAGE VERSIONS:                                                             
backpack/basset: 1.2.0                                                                     
backpack/crud: 6.2.0                                                                       
backpack/generators: v4.0.2                                                                
backpack/permissionmanager: 7.0.1                                                          
backpack/pro: 2.0.11                                                                       
backpack/theme-tabler: 1.1.0                                                               
```

**Comment by Mirko-Tebaldi** [comment]
We tried also to remove vendor folder at all
Do a fresh composer install
Remove \public\storage simlink 
Remove \storage\app\public\basset folder
Did a `opt:clear` and a `basset:clear`

Anyway, analyzing html source we can find a list of not-local assets.

![image](https://github.com/Laravel-Backpack/basset/assets/114985433/6ab32bd3-4fa5-4f70-8c6c-ac39f53fd7a4)

**Comment by pxpm** [comment]
> Thanks, but we have same problem with a fresh install on a clean project.
> 
> Anyway we'll try. I'll tell you in a few day due to my holidays
> 
> How to upgrade tabler? I hoped it will be upgraded when upgrading backpack
> 
> [please document it]
> 
> We have nothing published and only 1-2 small blades ovverriden [buttons and filters]

Check you `.env` file. The basset is automatically disabled in local https://github.com/Laravel-Backpack/basset#installation

**Comment by Mirko-Tebaldi** [comment]
How can be disabled if there are rows like this?

    <script src="/storage/basset/vendor/backpack/theme-tabler/resources/assets/js/tabler.js?b066c6427562"></script>

**Comment by pxpm** [comment]
The "non-public" files (the ones backpack load from vendor folder) need to be "internalized" everytime because they are in a non-accessible folder. 

The public cdn links and other javscript in files don't get internalized when basset is disabled so that you are always working with a "fresh" copy.
