### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by Astriel** [Laravel-Backpack/basset#95]
Hello everyone, 

I hope you are doing good. I've integrated backpack on my current project. I'm using Windows 10 + Laragon. Everything went fine, then I've switch to another branch, then came back on the one with Backpack integration and the design is now broken. 

Everything is installed, except I can't make basset work, so that's probably why my whole admin UI is broken ? 

Here is what I got : 

```
php artisan basset:check

   INFO  Checking Backpack Basset installation.

  Initializing basset check ................................................................................................................... DONE
  Checking cache storage ...................................................................................................................... DONE
  Fetching a basset .......................................................................................................................... ERROR

   ERROR  cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://myproject.local/storage/basset/vendor/backpack/basset/tests/Helpers/basset-test.js.
```

```
### PHP VERSION:
PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies

### LARAVEL VERSION:
10.21.1.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.2.0
backpack/crud: 6.2.0
backpack/devtools: 2.0.3
backpack/generators: v4.0.2
backpack/permissionmanager: 7.0.1
backpack/pro: 2.0.11
backpack/theme-coreuiv4: 1.1.0
```

SSL is working fine on localhost, but can't manage to get rid of the error. Any feedback ? 
Thanks a lot !

**Comment by Astriel** [comment]
This is what the design looks like : 

![image](https://github.com/Laravel-Backpack/basset/assets/4165153/9b3a5c0d-fe03-4017-a9b1-ac1477fce048)

**Comment by promatik** [comment]
Hi Astriel! Thank you for your report, I've just pushed a fix for your issue 👌
I was able to reproduce it using Laragon.

Basically cURL doesn't like self signed certificates, so in dev mode we disable the check for the certificate 🤷‍♂️

Let's move conversation to https://github.com/Laravel-Backpack/basset/pull/96.
